FROM node:20-slim AS build-stage
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

COPY package*.json /app/
COPY pnpm-lock.yaml /app/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

RUN pnpx playwright install --with-deps

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}
ARG VITE_USE_DEVTOOLS=${VITE_USE_DEVTOOLS}
