// This file is auto-generated by @hey-api/openapi-ts

export type AllFilter = 'all';

export type Body_admin_admin_login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KioskOrderCreate = {
    ordered_menus: Array<OrderedMenuCreate>;
    table_id: string;
    phone: string;
};

export type MenuOrderStatus = 'ordered' | 'rejected' | 'cooking' | 'served';

export type MenuPublic = {
    name: string;
    desc?: (string | null);
    /**
     * price in won
     */
    price: number;
    image?: (string | null);
    bg_color?: (string | null);
    category?: (string | null);
    no_stock?: boolean;
    id: string;
    created_at: string;
};

export type Menus = {
    name: string;
    desc?: (string | null);
    /**
     * price in won
     */
    price: number;
    image?: (string | null);
    bg_color?: (string | null);
    category?: (string | null);
    no_stock?: boolean;
    id?: string;
    restaurant_id: string;
    created_at?: string;
};

export type MenuUpdate = {
    no_stock?: (boolean | null);
};

export type OrderedMenuCreate = {
    menu_id: string;
    amount: number;
};

export type OrderedMenuForServing = {
    amount: number;
    reject_reason?: (string | null);
    cook_started_at?: (string | null);
    served_at?: (string | null);
    id: string;
    status: MenuOrderStatus;
    menu: MenuPublic;
    order_no: number;
    table_no: number;
};

export type OrderedMenuPublic = {
    amount: number;
    reject_reason?: (string | null);
    cook_started_at?: (string | null);
    served_at?: (string | null);
    id: string;
    status: MenuOrderStatus;
    menu: MenuPublic;
};

export type OrderedMenus = {
    amount: number;
    reject_reason?: (string | null);
    cook_started_at?: (string | null);
    served_at?: (string | null);
    id?: string;
    restaurant_id: string;
    order_id: string;
    menu_id: string;
    created_at?: string;
};

export type OrderedMenuUpdate = {
    cook_started_at?: (string | null);
    served_at?: (string | null);
    reject_reason?: (string | null);
};

export type OrderPublic = {
    reject_reason?: (string | null);
    finished_at?: (string | null);
    created_at?: string;
    id: string;
    no: number;
    status: OrderStatus;
    total_price: number;
    final_price: number;
    ordered_menus: Array<OrderedMenuPublic>;
    payment: (Payments | null);
    payment_info?: (PaymentInfo | null);
};

export type Orders = {
    reject_reason?: (string | null);
    finished_at?: (string | null);
    created_at?: string;
    id?: string;
    restaurant_id: string;
    team_id: string;
    payment_id?: (string | null);
    no?: (number | null);
};

export type OrderStatus = 'ordered' | 'paid' | 'rejected' | 'finished';

export type OrderUpdate = {
    payment_id?: (string | null);
    finished_at?: (string | null);
    reject_reason?: (string | null);
};

/**
 * 주문과 팀 정보를 함께 반환하는 모델
 */
export type OrderWithTeamInfo = {
    reject_reason?: (string | null);
    finished_at?: (string | null);
    created_at?: string;
    id: string;
    no: number;
    status: OrderStatus;
    total_price: number;
    final_price: number;
    ordered_menus: Array<OrderedMenuPublic>;
    payment: (Payments | null);
    payment_info: PaymentInfo;
    team: TeamPublic;
};

export type PaymentInfo = {
    bank_name: string;
    bank_account_no: string;
};

export type Payments = {
    id?: string;
    restaurant_id: string;
    transaction_by?: (string | null);
    amount: number;
    refunded_at?: (string | null);
    created_at?: string;
};

export type Restaurants = {
    id?: string;
    name?: string;
    open_time: string;
    close_time: string;
    break_start_time: (string | null);
    break_end_time: (string | null);
    created_at?: string;
};

export type RestaurantUpdate = {
    break_start_time?: (string | null);
    break_end_time?: (string | null);
};

/**
 * 테이블 ID로 직접 주문 생성 (팀도 함께 생성)
 */
export type TableOrderCreate = {
    table_id: string;
    ordered_menus: Array<OrderedMenuCreate>;
};

export type Tables = {
    id?: string;
    restaurant_id: string;
    no: number;
    status?: TableStatus;
    created_at?: string;
};

export type TableStatus = 'idle' | 'in_use' | 'reserved';

export type TableUpdate = {
    status: TableStatus;
};

export type TeamPublic = {
    id: string;
    table: Tables;
    ended_at?: (string | null);
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WaitingCreate = {
    name: string;
    phone: string;
};

export type WaitingFind = {
    name: string;
    phone: string;
};

export type Waitings = {
    id?: string;
    restaurant_id: string;
    name: string;
    phone: string;
    notified_at?: (string | null);
    entered_at?: (string | null);
    rejected_at?: (string | null);
    rejected_reason?: (string | null);
    created_at?: string;
};

export type WaitingStatus = 'waiting' | 'notified' | 'entered' | 'rejected';

export type AdminAdminLoginData = {
    formData: Body_admin_admin_login;
};

export type AdminAdminLoginResponse = (Token);

export type AdminUpdateRestaurantData = {
    requestBody: RestaurantUpdate;
};

export type AdminUpdateRestaurantResponse = (Restaurants);

export type AdminUpdateMenuData = {
    menuId: string;
    requestBody: MenuUpdate;
};

export type AdminUpdateMenuResponse = (Menus);

export type AdminReadTablesData = {
    status?: (TableStatus | AllFilter);
};

export type AdminReadTablesResponse = (Array<Tables>);

export type AdminUpdateTableData = {
    requestBody: TableUpdate;
    tableId: string;
};

export type AdminUpdateTableResponse = (Tables);

export type AdminReadWaitingsData = {
    status?: (WaitingStatus | AllFilter);
};

export type AdminReadWaitingsResponse = (Array<Waitings>);

export type AdminDequeueWaitingsData = {
    dequeueCount?: number;
};

export type AdminDequeueWaitingsResponse = (Array<Waitings>);

export type AdminRejectWaitingData = {
    reason?: string;
    waitingId: string;
};

export type AdminRejectWaitingResponse = ({
    [key: string]: unknown;
});

export type AdminCreateKioskOrderData = {
    requestBody: KioskOrderCreate;
};

export type AdminCreateKioskOrderResponse = (OrderWithTeamInfo);

export type AdminReadOrdersData = {
    status?: (OrderStatus | AllFilter);
};

export type AdminReadOrdersResponse = (Array<OrderPublic>);

export type AdminReadOrderData = {
    orderId: string;
};

export type AdminReadOrderResponse = (OrderPublic);

export type AdminUpdateOrderData = {
    orderId: string;
    requestBody: OrderUpdate;
};

export type AdminUpdateOrderResponse = (Orders);

export type AdminRejectOrderData = {
    orderId: string;
    reason?: string;
};

export type AdminRejectOrderResponse = ({
    [key: string]: unknown;
});

export type AdminUpdateMenuOrderData = {
    menuId: string;
    orderId: string;
    requestBody: OrderedMenuUpdate;
};

export type AdminUpdateMenuOrderResponse = (OrderedMenus);

export type AdminRejectMenuOrderData = {
    menuId: string;
    orderId: string;
    reason?: string;
};

export type AdminRejectMenuOrderResponse = ({
    [key: string]: unknown;
});

export type AdminGetCookedOrderedMenusResponse = (Array<OrderedMenuForServing>);

export type AdminServeOrderedMenuData = {
    orderedMenuId: string;
};

export type AdminServeOrderedMenuResponse = (OrderedMenus);

export type AdminReadPaymentsResponse = (Array<Payments>);

export type AdminRefundPaymentData = {
    paymentId: string;
};

export type AdminRefundPaymentResponse = (Payments);

export type MenusReadMenusResponse = (Array<MenuPublic>);

export type OrdersCreateOrderData = {
    requestBody: TableOrderCreate;
};

export type OrdersCreateOrderResponse = (OrderWithTeamInfo);

export type OrdersReadOrdersByTableData = {
    tableId: string;
};

export type OrdersReadOrdersByTableResponse = (Array<Orders>);

export type RestaurantsReadRestaurantsResponse = (Restaurants);

export type UtilsHealthCheckResponse = (boolean);

export type WaitingsReadWatingsData = {
    requestBody: WaitingFind;
};

export type WaitingsReadWatingsResponse = (Array<Waitings>);

export type WaitingsEnqueueWaitingsData = {
    requestBody: WaitingCreate;
};

export type WaitingsEnqueueWaitingsResponse = (Waitings);

export type WaitingsCancelWaitingData = {
    requestBody: WaitingFind;
};

export type WaitingsCancelWaitingResponse = (unknown);