"""remove_cook_started_at_column

Revision ID: 314346265642
Revises: 3f0c10f141a0
Create Date: 2025-09-14 19:31:57.830465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '314346265642'
down_revision = '3f0c10f141a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderedmenus', 'cook_started_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderedmenus', sa.Column('cook_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
