"""add_cooked_amount_to_ordered_menus

Revision ID: 3f0c10f141a0
Revises: 6b1e711679a9
Create Date: 2025-09-14 19:24:19.159071

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "3f0c10f141a0"
down_revision = "6b1e711679a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orderedmenus",
        sa.Column("cooked_amount", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orderedmenus", "cooked_amount")
    # ### end Alembic commands ###
