"""add menu category

Revision ID: 4311a59fa22d
Revises: 9dd981320b96
Create Date: 2025-09-01 22:27:10.689542

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4311a59fa22d'
down_revision = '9dd981320b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_menus_category'), 'menus', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_category'), table_name='menus')
    op.drop_column('menus', 'category')
    # ### end Alembic commands ###
