"""add optional phone column in teams

Revision ID: 435564d85da7
Revises: deedab294130
Create Date: 2025-09-13 16:24:20.945501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '435564d85da7'
down_revision = 'deedab294130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('teams', 'table_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_teams_phone'), 'teams', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_phone'), table_name='teams')
    op.alter_column('teams', 'table_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('teams', 'phone')
    # ### end Alembic commands ###
