"""initlalize_models

Revision ID: 56341f80ec43
Revises:
Create Date: 2025-08-24 18:22:03.799292

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "56341f80ec43"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("desc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("no_stock", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menus_title"), "menus", ["title"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("no", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("idle", "in_use", "reserved", name="tablestatus"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tables_status"), "tables", ["status"], unique=False)
    op.create_table(
        "waitings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_waitings_name"), "waitings", ["name"], unique=False)
    op.create_index(op.f("ix_waitings_phone"), "waitings", ["phone"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("waiting_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.id"],
        ),
        sa.ForeignKeyConstraint(
            ["waiting_id"],
            ["waitings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_table_id"), "teams", ["table_id"], unique=False)
    op.create_index(op.f("ix_teams_waiting_id"), "teams", ["waiting_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("cook_started_at", sa.DateTime(), nullable=True),
        sa.Column("served_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_payment_id"), "orders", ["payment_id"], unique=False
    )
    op.create_index(op.f("ix_orders_team_id"), "orders", ["team_id"], unique=False)
    op.create_table(
        "menuorders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("menu_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["menus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_menuorders_menu_id"), "menuorders", ["menu_id"], unique=False
    )
    op.create_index(
        op.f("ix_menuorders_order_id"), "menuorders", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_menuorders_order_id"), table_name="menuorders")
    op.drop_index(op.f("ix_menuorders_menu_id"), table_name="menuorders")
    op.drop_table("menuorders")
    op.drop_index(op.f("ix_orders_team_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_payment_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_teams_waiting_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_table_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_waitings_phone"), table_name="waitings")
    op.drop_index(op.f("ix_waitings_name"), table_name="waitings")
    op.drop_table("waitings")
    op.drop_index(op.f("ix_tables_status"), table_name="tables")
    op.drop_table("tables")
    op.drop_table("payments")
    op.drop_index(op.f("ix_menus_title"), table_name="menus")
    op.drop_table("menus")
    # ### end Alembic commands ###
