"""Add is_instant_serve field to menus

Revision ID: 6b1e711679a9
Revises: a36468d16ccc
Create Date: 2025-09-14 18:34:54.661779

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "6b1e711679a9"
down_revision = "a36468d16ccc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menus",
        sa.Column("is_instant_serve", sa.Boolean(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menus", "is_instant_serve")
    # ### end Alembic commands ###
