"""change some nullable fields

Revision ID: 9dd981320b96
Revises: 2b5f57c2c098
Create Date: 2025-08-26 05:01:46.249716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9dd981320b96'
down_revision = '2b5f57c2c098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'team_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'no',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('orders_no_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'no',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('orders_no_seq'::regclass)"))
    op.alter_column('orders', 'team_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
