"""modify teams

Revision ID: deedab294130
Revises: 3c873bed0b5c
Create Date: 2025-09-12 20:34:22.968017

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'deedab294130'
down_revision = '3c873bed0b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orderedmenus_order_id_fkey', 'orderedmenus', type_='foreignkey')
    op.create_foreign_key(None, 'orderedmenus', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('teams', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'ended_at')
    op.drop_constraint(None, 'orderedmenus', type_='foreignkey')
    op.create_foreign_key('orderedmenus_order_id_fkey', 'orderedmenus', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
