"""add ondelete options

Revision ID: e79a656df218
Revises: 435564d85da7
Create Date: 2025-09-13 23:17:50.282159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e79a656df218'
down_revision = '435564d85da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_team_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_restaurant_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('payments_restaurant_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tables_restaurant_id_fkey', 'tables', type_='foreignkey')
    op.create_foreign_key(None, 'tables', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('teams_restaurant_id_fkey', 'teams', type_='foreignkey')
    op.drop_constraint('teams_table_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teams', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('waitings_restaurant_id_fkey', 'waitings', type_='foreignkey')
    op.create_foreign_key(None, 'waitings', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitings', type_='foreignkey')
    op.create_foreign_key('waitings_restaurant_id_fkey', 'waitings', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_table_id_fkey', 'teams', 'tables', ['table_id'], ['id'])
    op.create_foreign_key('teams_restaurant_id_fkey', 'teams', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.create_foreign_key('tables_restaurant_id_fkey', 'tables', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_restaurant_id_fkey', 'payments', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_restaurant_id_fkey', 'orders', 'restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key('orders_team_id_fkey', 'orders', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
